sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: x
    database: sky_take_out
    username: root
    password: x
  alioss:
    endpoint:x
    access-key-id: x
    access-key-secret: Bx
    bucket-name: x
