sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: a123456788
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNJ8X4Kr9PXLMPoSixm
    access-key-secret: B4XpqJt4DTlF4OidTxxm21SqfEPfA8
    bucket-name: web-tliass212
